export const RESET = "ANIMAL_UPDATE_RESET";
export const SET_ERROR = "ANIMAL_UPDATE_SET_ERROR";
export const SET_RETRIEVED = "ANIMAL_UPDATE_SET_RETRIEVED";
export const SET_HUB_URL = "ANIMAL_UPDATE_SET_HUB_URL";
export const SET_UPDATED = "ANIMAL_UPDATE_SET_UPDATED";
export const SET_VIOLATIONS = "ANIMAL_UPDATE_SET_VIOLATIONS";
export const TOGGLE_LOADING = "ANIMAL_UPDATE_TOGGLE_LOADING";
export const UPDATE_RETRIEVED = "ANIMAL_UPDATE_UPDATE_RETRIEVED";
