export const RESET = "PROPRIETAIRE_UPDATE_RESET";
export const SET_ERROR = "PROPRIETAIRE_UPDATE_SET_ERROR";
export const SET_RETRIEVED = "PROPRIETAIRE_UPDATE_SET_RETRIEVED";
export const SET_HUB_URL = "PROPRIETAIRE_UPDATE_SET_HUB_URL";
export const SET_UPDATED = "PROPRIETAIRE_UPDATE_SET_UPDATED";
export const SET_VIOLATIONS = "PROPRIETAIRE_UPDATE_SET_VIOLATIONS";
export const TOGGLE_LOADING = "PROPRIETAIRE_UPDATE_TOGGLE_LOADING";
export const UPDATE_RETRIEVED = "PROPRIETAIRE_UPDATE_UPDATE_RETRIEVED";
