export const ANIMAL_CREATE_RESET = "ANIMAL_CREATE_RESET";
export const ANIMAL_CREATE_SET_CREATED = "ANIMAL_CREATE_SET_CREATED";
export const ANIMAL_CREATE_SET_ERROR = "ANIMAL_CREATE_SET_ERROR";
export const ANIMAL_CREATE_SET_VIOLATIONS = "ANIMAL_CREATE_SET_VIOLATIONS";
export const ANIMAL_CREATE_TOGGLE_LOADING = "ANIMAL_CREATE_TOGGLE_LOADING";
