export const PROPRIETAIRE_SHOW_RESET = "PROPRIETAIRE_SHOW_RESET";
export const PROPRIETAIRE_SHOW_SET_ERROR = "PROPRIETAIRE_SHOW_SET_ERROR";
export const PROPRIETAIRE_SHOW_SET_RETRIEVED =
  "PROPRIETAIRE_SHOW_SET_RETRIEVED";
export const PROPRIETAIRE_SHOW_SET_HUB_URL = "PROPRIETAIRE_SHOW_SET_HUB_URL";
export const PROPRIETAIRE_SHOW_TOGGLE_LOADING =
  "PROPRIETAIRE_SHOW_TOGGLE_LOADING";
