export const ANIMAL_SHOW_RESET = "ANIMAL_SHOW_RESET";
export const ANIMAL_SHOW_SET_ERROR = "ANIMAL_SHOW_SET_ERROR";
export const ANIMAL_SHOW_SET_RETRIEVED = "ANIMAL_SHOW_SET_RETRIEVED";
export const ANIMAL_SHOW_SET_HUB_URL = "ANIMAL_SHOW_SET_HUB_URL";
export const ANIMAL_SHOW_TOGGLE_LOADING = "ANIMAL_SHOW_TOGGLE_LOADING";
