export const ANIMAL_DELETE_RESET = "ANIMAL_DELETE_RESET";
export const ANIMAL_DELETE_SET_ERROR = "ANIMAL_DELETE_SET_ERROR";
export const ANIMAL_DELETE_SET_DELETED = "ANIMAL_DELETE_SET_DELETED";
export const ANIMAL_DELETE_MERCURE_SET_DELETED =
  "ANIMAL_DELETE_MERCURE_SET_DELETED";
export const ANIMAL_DELETE_TOGGLE_LOADING = "ANIMAL_DELETE_TOGGLE_LOADING";
