export const PROPRIETAIRE_CREATE_RESET = "PROPRIETAIRE_CREATE_RESET";
export const PROPRIETAIRE_CREATE_SET_CREATED =
  "PROPRIETAIRE_CREATE_SET_CREATED";
export const PROPRIETAIRE_CREATE_SET_ERROR = "PROPRIETAIRE_CREATE_SET_ERROR";
export const PROPRIETAIRE_CREATE_SET_VIOLATIONS =
  "PROPRIETAIRE_CREATE_SET_VIOLATIONS";
export const PROPRIETAIRE_CREATE_TOGGLE_LOADING =
  "PROPRIETAIRE_CREATE_TOGGLE_LOADING";
