export const PROPRIETAIRE_DELETE_RESET = "PROPRIETAIRE_DELETE_RESET";
export const PROPRIETAIRE_DELETE_SET_ERROR = "PROPRIETAIRE_DELETE_SET_ERROR";
export const PROPRIETAIRE_DELETE_SET_DELETED =
  "PROPRIETAIRE_DELETE_SET_DELETED";
export const PROPRIETAIRE_DELETE_MERCURE_SET_DELETED =
  "PROPRIETAIRE_DELETE_MERCURE_SET_DELETED";
export const PROPRIETAIRE_DELETE_TOGGLE_LOADING =
  "PROPRIETAIRE_DELETE_TOGGLE_LOADING";
